# Generated by Django 2.2.2 on 2019-06-26 10:45

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitly',
            name='datewise',
            field=jsonfield.fields.JSONField(),
        ),
    ]
