# Generated by Django 2.2.2 on 2019-06-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_auto_20190626_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitly',
            name='datewise',
            field=models.TextField(),
        ),
    ]
