# Generated by Django 2.2.2 on 2019-06-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0003_auto_20190626_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitly',
            name='user',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
